--- 
title: "How The Cross Works"
author: "Adam M. Denoon Th.B."
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
classoption: openany
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
github-repo: adamdenoon/bookdown-crossworks
description: "A brief explanation of the centrality of the cross to our daily faith."
---

# Preface {-}

This is a _simple_ explanation of the centrality of the Cross of Christ to our daily faith. Since it is intended to be a broad overview of the subject, the reader should not expect a detailed, theological discourse. What the reader should expect is something that resembles the subject of II Corinthians 11:3:

> "But I fear, lest by any means, as the serpent beguiled Eve through his subtilty, so your minds should be corrupted from the _simplicity_^[Gk. ἁπλότης/haplótes; "purity, simplicity, singleness"; The idea is that of having nothing impure mixed in (nothing to "muddy the waters"); Simple, pure, honest.] that is in Christ."
> - II Corinthians 11:3

In an attempt to keep the present discourse as simple and pure as possible, the author has wrapped this complex subject into a simple set of illustrations. Despite the simplicitly, however, the reader should be confident of the accuracy of the explanation. Scriptural references are provided for personal study, as well as detailed explanations in the footnotes.
